# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Image:
  fields:
    default: title, image, caption
    form: title, image, caption
  order_by: title 
  relationships:  
  filters: created_at
  search: title
  application: Real Estate CMS

